# Black
[tool.black]
line-length = 88

# iSort
[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true

# Flake8
[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "E501"]
